export default function handler(req, res) {
  const data = [
    {
      id: 2,
      details: 'Robbed at Illupeju ATm',
      user_id: 6,
      bank_id: 1,
      amount: '45,000',
      incident_status_id: 16,
      is_verified: 0,
      is_closed: 0,
      created_at: '2023-08-21T17:18:26.000000Z',
      updated_at: null,
      deleted_at: null,
    },
    {
      id: 3,
      details: 'Receiveng debit alerts and my atm and bank app is with me',
      user_id: 5,
      bank_id: 5,
      amount: '2,000,000',
      incident_status_id: 16,
      is_verified: 0,
      is_closed: 0,
      created_at: '2023-08-21T17:20:03.000000Z',
      updated_at: null,
      deleted_at: null,
    },
    {
      id: 4,
      details:
        "Paid money into another person's account. Now the person doesn't want to return it",
      user_id: 6,
      bank_id: 8,
      amount: '50,000',
      incident_status_id: 16,
      is_verified: 0,
      is_closed: 0,
      created_at: '2023-08-21T17:20:50.000000Z',
      updated_at: null,
      deleted_at: null,
    },
    {
      id: 5,
      details: 'I lost my money to a Mallam',
      user_id: 6,
      bank_id: 10,
      amount: '500,000',
      incident_status_id: 16,
      is_verified: 0,
      is_closed: 0,
      created_at: '2023-08-21T16:42:31.000000Z',
      updated_at: '2023-08-21T16:42:31.000000Z',
      deleted_at: null,
    },
    {
      id: 8,
      details: 'I was robbed at work',
      user_id: 6,
      bank_id: 10,
      amount: '32,000',
      incident_status_id: 16,
      is_verified: 0,
      is_closed: 0,
      created_at: '2023-08-22T12:34:31.000000Z',
      updated_at: '2023-08-22T12:34:31.000000Z',
      deleted_at: null,
    },
    {
      id: 9,
      details: 'I was robbed by Finn',
      user_id: 6,
      bank_id: 10,
      amount: '2,000,00',
      incident_status_id: 16,
      is_verified: 0,
      is_closed: 0,
      created_at: '2023-08-22T12:56:45.000000Z',
      updated_at: '2023-08-22T12:56:45.000000Z',
      deleted_at: null,
    },
    {
      id: 10,
      details: 'Necessitatibus optio consequatur est iusto magni.',
      user_id: 5,
      bank_id: 2,
      amount: '502906',
      incident_status_id: 17,
      is_verified: 0,
      is_closed: 0,
      created_at: null,
      updated_at: null,
      deleted_at: null,
    },
    {
      id: 11,
      details: 'Cupiditate quidem porro possimus tempora autem voluptate non.',
      user_id: 5,
      bank_id: 2,
      amount: '703963',
      incident_status_id: 17,
      is_verified: 0,
      is_closed: 0,
      created_at: null,
      updated_at: null,
      deleted_at: null,
    },
    {
      id: 12,
      details: 'Voluptatem consequatur perspiciatis ducimus ab adipisci.',
      user_id: 5,
      bank_id: 14,
      amount: '309675',
      incident_status_id: 1,
      is_verified: 0,
      is_closed: 0,
      created_at: null,
      updated_at: null,
      deleted_at: null,
    },
    {
      id: 13,
      details: 'Aut voluptatem et illum doloremque quos et.',
      user_id: 6,
      bank_id: 24,
      amount: '488274',
      incident_status_id: 17,
      is_verified: 0,
      is_closed: 0,
      created_at: null,
      updated_at: null,
      deleted_at: null,
    },
    {
      id: 14,
      details: 'Dolor atque ullam aperiam minima ipsum et.',
      user_id: 5,
      bank_id: 41,
      amount: '547471',
      incident_status_id: 1,
      is_verified: 0,
      is_closed: 0,
      created_at: null,
      updated_at: null,
      deleted_at: null,
    },
    {
      id: 15,
      details: 'Maiores eos neque provident aut veniam.',
      user_id: 6,
      bank_id: 34,
      amount: '194106',
      incident_status_id: 17,
      is_verified: 0,
      is_closed: 0,
      created_at: null,
      updated_at: null,
      deleted_at: null,
    },
    {
      id: 16,
      details: 'Sapiente sunt neque sint est modi.',
      user_id: 6,
      bank_id: 30,
      amount: '160203',
      incident_status_id: 1,
      is_verified: 0,
      is_closed: 0,
      created_at: null,
      updated_at: null,
      deleted_at: null,
    },
    {
      id: 17,
      details: 'Officiis possimus earum dolores tempora minus.',
      user_id: 5,
      bank_id: 22,
      amount: '664853',
      incident_status_id: 1,
      is_verified: 0,
      is_closed: 0,
      created_at: null,
      updated_at: null,
      deleted_at: null,
    },
    {
      id: 18,
      details: 'Veniam eligendi consequatur voluptates non.',
      user_id: 6,
      bank_id: 25,
      amount: '758634',
      incident_status_id: 1,
      is_verified: 0,
      is_closed: 0,
      created_at: null,
      updated_at: null,
      deleted_at: null,
    },
    {
      id: 19,
      details: 'Dolores molestiae magnam sit numquam ut aut aut.',
      user_id: 5,
      bank_id: 19,
      amount: '132292',
      incident_status_id: 1,
      is_verified: 0,
      is_closed: 0,
      created_at: null,
      updated_at: null,
      deleted_at: null,
    },
    {
      id: 20,
      details: 'Accusamus ducimus expedita et nemo eum cupiditate.',
      user_id: 5,
      bank_id: 43,
      amount: '585628',
      incident_status_id: 1,
      is_verified: 0,
      is_closed: 0,
      created_at: null,
      updated_at: null,
      deleted_at: null,
    },
    {
      id: 21,
      details: 'Ipsa harum sunt velit illo autem et.',
      user_id: 6,
      bank_id: 26,
      amount: '408796',
      incident_status_id: 1,
      is_verified: 0,
      is_closed: 0,
      created_at: null,
      updated_at: null,
      deleted_at: null,
    },
    {
      id: 22,
      details: 'Consequatur natus inventore dolorem ut voluptatem.',
      user_id: 5,
      bank_id: 7,
      amount: '349891',
      incident_status_id: 17,
      is_verified: 0,
      is_closed: 0,
      created_at: null,
      updated_at: null,
      deleted_at: null,
    },
    {
      id: 23,
      details: 'Quis omnis commodi aut molestias voluptas sed consequatur.',
      user_id: 5,
      bank_id: 8,
      amount: '661776',
      incident_status_id: 17,
      is_verified: 0,
      is_closed: 0,
      created_at: null,
      updated_at: null,
      deleted_at: null,
    },
    {
      id: 24,
      details: 'Nemo id quis mollitia quod nobis nobis.',
      user_id: 6,
      bank_id: 3,
      amount: '759858',
      incident_status_id: 1,
      is_verified: 0,
      is_closed: 0,
      created_at: null,
      updated_at: null,
      deleted_at: null,
    },
    {
      id: 25,
      details: 'Voluptatem blanditiis repellat ratione aut aperiam.',
      user_id: 5,
      bank_id: 22,
      amount: '130431',
      incident_status_id: 1,
      is_verified: 0,
      is_closed: 0,
      created_at: null,
      updated_at: null,
      deleted_at: null,
    },
    {
      id: 26,
      details: 'Et rerum iusto ex officia quo.',
      user_id: 6,
      bank_id: 6,
      amount: '506425',
      incident_status_id: 17,
      is_verified: 0,
      is_closed: 0,
      created_at: null,
      updated_at: null,
      deleted_at: null,
    },
    {
      id: 27,
      details: 'Accusantium nemo sed tempore.',
      user_id: 6,
      bank_id: 27,
      amount: '154819',
      incident_status_id: 1,
      is_verified: 0,
      is_closed: 0,
      created_at: null,
      updated_at: null,
      deleted_at: null,
    },
    {
      id: 28,
      details: 'Aut mollitia nesciunt aut distinctio assumenda.',
      user_id: 6,
      bank_id: 20,
      amount: '656155',
      incident_status_id: 17,
      is_verified: 0,
      is_closed: 0,
      created_at: null,
      updated_at: null,
      deleted_at: null,
    },
    {
      id: 29,
      details: 'Aut suscipit laboriosam atque cum.',
      user_id: 6,
      bank_id: 37,
      amount: '534965',
      incident_status_id: 17,
      is_verified: 0,
      is_closed: 0,
      created_at: null,
      updated_at: null,
      deleted_at: null,
    },
  ];
  res.status(200).json({ data });
}
